### ISSUE TITLE
Inconsistent python use

### ISSUE THREAD

**Issue by sroet** [dgoldsb/tipsitutorial#1]
I did your whole tutorial, however I ran into some issues using your python scripts:

First was in generate2Dbins.py, if that is run with python 3 it raises an error:

```
Traceback (most recent call last):
  File "../../bin/generate2Dbins.py", line 63, in <module>
    var1 = var1[row1] #var1[row1,:]
IndexError: too many indices for array
```

This works fine in python 2, however further in your tutorial when I try to run processTIPSImerge.py in python 2 it raises the error:

```
Traceback (most recent call last):
  File "processTIPSImerge.py", line 5, in <module>
    from tkinter import *
ImportError: No module named tkinter

```

This is becaue in python 2.x the package is called "Tkinter"

**Comment by dgoldsb** [comment]
Thanks for letting me know, I will look into it when I have my desktop available again Friday!

**Comment by dgoldsb** [comment]
I have altered both scripts to run on both python 2 and 3.
